services:
  server:
    image: ghcr.io/ZhongFuze/solana-name-indexer:main
    container_name: solana-name-indexer
    network_mode: "host"
    volumes:
      - ~/solana-name-indexer/data:/node_app/data
      - ~/solana-name-indexer/.env:/node_app/.env
      - ~/solana-name-indexer/log:/tmp