[unix_http_server]
file=/var/tmp/solana_name_indexer.supervior.sock
chmod=0760

[supervisord]
nodaemon=true
logfile=/var/tmp/solana_name_indexer_supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
user=root

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl = unix:///var/tmp/solana_name_indexer.supervior.sock

; use nodaemon to start proc
[program:solana_name_indexer]
command=node --no-deprecation index.js
autostart=true
autorestart=false
stopsignal=KILL
stopasgroup=true
killasgroup=true
